# Generated by Django 4.2.4 on 2024-07-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='author',
            new_name='user',
        ),
    ]
