# Generated by Django 4.2.4 on 2024-09-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_comment_likes_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
